disabled_rules:
  - trailing_whitespace
  - multiple_closures_with_trailing_closure

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - contains_over_first_not_nil
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - strict_fileprivate
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

analyzer_rules:
  - unused_declaration
  - unused_import

included:
  - Sources
  - Tests

excluded:
  - "**/*.generated.swift"
  - .build

line_length:
  warning: 120
  error: 200

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_name:
  min_length: 3
  max_length: 40

identifier_name:
  min_length: 2
  max_length: 40

nesting:
  type_level: 2

cyclomatic_complexity:
  warning: 10
  error: 20

reporter: "xcode"
