platform :ios, '17.0'

target 'XcalpClinic' do
  use_frameworks!
  
  # Core Dependencies
  pod 'RxSwift', '~> 6.6.0'
  pod 'RxCocoa', '~> 6.6.0'
  
  # ML & Vision
  pod 'MLKitVision', '~> 5.0.0'
  pod 'TensorFlowLiteSwift', '~> 2.13.0'
  
  # Image Processing
  pod 'GPUImage2', '~> 0.3.0'
  pod 'OpenCV', '~> 4.9.0'
  
  # Analytics & Monitoring
  pod 'FirebaseAnalytics', '~> 10.29.0'
  pod 'FirebaseCrashlytics', '~> 10.29.0'
  
  # Security & Compliance
  pod 'HIPAACompliantStorage', '~> 3.2.0'
  pod 'GDPRComplianceKit', '~> 2.1.0'
  pod 'CryptoSwift', '~> 1.7.0'
  
  # Testing
  target 'XcalpClinicTests' do
    inherit! :search_paths
    pod 'Quick', '~> 7.3.0'
    pod 'Nimble', '~> 13.1.2'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['OTHER_SWIFT_FLAGS'] = '-D HIPAA_COMPLIANCE -D GDPR_COMPLIANCE'
      
      # Enable Metal API validation for debug builds
      if config.name == 'Debug'
        config.build_settings['MTL_ENABLE_DEBUG_LAYER'] = 'YES'
      end
    end
  end
end
