name: XcalpClinic
options:
  deploymentTarget:
    iOS: 17.0
  bundleIdPrefix: com.xcalp
  createIntermediateGroups: true
  usesTabs: false
  indentWidth: 2
  tabWidth: 2
  developmentLanguage: en
  packagePaths:
    - path: .
    - package: Package.swift
  enableBaseConfigurationInvariants: true
  settingPresets: all
  enableUpcomingFeature:
    - BareSlashRegexLiterals
    - ExistentialAny
    - ForwardTrailingClosures
    - SwiftSupport
    - MacroSupport
  enableBaseInternationalization: true
  groupSortPosition: top
  transitivelyLinkDependencies: true
  useBaseInternationalization: true
  enableSwiftPackageManagerMacros: true

packages:
  TCA:
    url: https://github.com/pointfreeco/swift-composable-architecture
    exactVersion: 1.17.1
  CasePaths:
    url: https://github.com/pointfreeco/swift-case-paths
    exactVersion: 1.6.1
  Dependencies:
    url: https://github.com/pointfreeco/swift-dependencies
    exactVersion: 1.7.0
  Perception:
    url: https://github.com/pointfreeco/swift-perception
    exactVersion: 1.5.0
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    exactVersion: 4.2.2
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    exactVersion: 10.29.0

targets:
  XcalpClinic:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - path: Sources/XcalpClinic
    resources:
      - path: Sources/XcalpClinic/Resources
        includes:
          - "**/*.xcassets"
          - "**/*.storyboard"
          - "**/*.strings"
          - "**/*.stringsdict"
          - "**/*.ttf"
          - "**/*.otf"
          - "**/*.metal"
    info:
      path: Sources/XcalpClinic/Resources/Info.plist
      properties:
        CFBundleDisplayName: Xcalp Clinic
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIRequiredDeviceCapabilities: [armv7, arkit, metal, lidar]
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSCameraUsageDescription: "Xcalp Clinic needs camera access for 3D scanning"
        NSPhotoLibraryUsageDescription: "Xcalp Clinic needs photo library access to save scans"
        NSMicrophoneUsageDescription: "Xcalp Clinic needs microphone access for voice guidance"
        NSLocationWhenInUseUsageDescription: "Xcalp Clinic needs location access for clinic information"
        NSFaceIDUsageDescription: "Xcalp Clinic uses Face ID to secure patient data"
        NSHealthShareUsageDescription: "Xcalp Clinic integrates with Health app for medical records"
        NSHealthUpdateUsageDescription: "Xcalp Clinic updates Health app with treatment data"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.xcalp.clinic
        DEVELOPMENT_TEAM: T7Q8Z3GMZM
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        PROVISIONING_PROFILE_SPECIFIER: ""
        TARGETED_DEVICE_FAMILY: 1,2
        SWIFT_VERSION: 5.9
        ENABLE_TESTING_SEARCH_PATHS: YES
        ENABLE_BITCODE: NO
        METAL_ENABLE_DEBUG_INFO: YES
        MTL_ENABLE_DEBUG_INFO: YES
        ENABLE_PREVIEWS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_ACTIVE_COMPILATION_CONDITIONS:
          - DEBUG
          - ENABLE_METAL
          - ENABLE_ARKIT
          - ENABLE_LIDAR
        OTHER_SWIFT_FLAGS: [
          "$(inherited)",
          "-load-plugin-library", "ComposableArchitectureMacros",
          "-load-plugin-library", "CasePathsMacros",
          "-load-plugin-library", "DependenciesMacrosPlugin",
          "-load-plugin-library", "PerceptionMacros",
          "-enable-bare-slash-regex"
        ]
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        OTHER_LDFLAGS: $(inherited) -ObjC
        SWIFT_STRICT_CONCURRENCY: complete
        SWIFT_ENABLE_MACRO_SUPPORT: YES
        OTHER_LDFLAGS: ["-Xlinker", "-interposable"]
    dependencies:
      - sdk: ARKit.framework
      - sdk: Metal.framework
      - package: TCA
        product: ComposableArchitecture
      - package: TCA
        product: ComposableArchitectureMacros
      - package: CasePaths
        product: CasePathsMacros
      - package: Dependencies
        product: DependenciesMacrosPlugin
      - package: Perception
        product: PerceptionMacros
      - package: KeychainAccess
        product: KeychainAccess
      - package: Firebase
        products:
          - FirebaseAnalytics
          - FirebaseAuth
    macros:
      - ComposableArchitectureMacros
      - CasePathsMacros
      - DependenciesMacrosPlugin
      - PerceptionMacros
    testTargets:
      - XcalpClinicTests
      - XcalpClinicUITests
    preBuildScripts:
      - name: SwiftLint
        script: |
          if which swiftlint >/dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed"
          fi
      - name: Metal Library Validation
        script: |
          xcrun metal -c "${SRCROOT}/Sources/XcalpClinic/Features/Treatment/RegionDetector.metal" -o "${DERIVED_FILE_DIR}/RegionDetector.air"
          xcrun metal -c "${SRCROOT}/Sources/XcalpClinic/Features/Processing/MeshShaders.metal" -o "${DERIVED_FILE_DIR}/MeshShaders.air"
          xcrun metallib "${DERIVED_FILE_DIR}/RegionDetector.air" "${DERIVED_FILE_DIR}/MeshShaders.air" -o "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/default.metallib"
        outputFiles:
          - $(BUILT_PRODUCTS_DIR)/$(UNLOCALIZED_RESOURCES_FOLDER_PATH)/default.metallib

  XcalpClinicTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - path: Tests/XcalpClinicTests
    dependencies:
      - target: XcalpClinic
    settings:
      base:
        SWIFT_VERSION: 5.9
        ENABLE_TESTING_SEARCH_PATHS: YES

  XcalpClinicUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - path: Tests/XcalpClinicUITests
    dependencies:
      - target: XcalpClinic
    settings:
      base:
        SWIFT_VERSION: 5.9
        ENABLE_TESTING_SEARCH_PATHS: YES
