platform :ios, '14.0'
use_frameworks!

target 'xcalp' do
  pod 'Alamofire', '~> 5.8.0'
  pod 'RxSwift', '~> 6.5.0'
  pod 'SwiftLint', '~> 0.52.0'
  pod 'ARKit'
  pod 'SceneKit'
  pod 'MetalKit'
  pod 'GPUImage'
  pod 'OpenCV'
  pod 'TensorFlowLiteSwift'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
      
      # Enable required device capabilities
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD'] = 'NO'
      
      # Add framework capabilities
      config.build_settings['OTHER_LDFLAGS'] ||= ['$(inherited)']
      config.build_settings['OTHER_LDFLAGS'] << '-framework ARKit'
      config.build_settings['OTHER_LDFLAGS'] << '-framework Metal'
      config.build_settings['OTHER_LDFLAGS'] << '-framework MetalKit'
      config.build_settings['OTHER_LDFLAGS'] << '-framework MetalPerformanceShaders'
      config.build_settings['OTHER_LDFLAGS'] << '-framework SceneKit'
    end
  end
end
