platform :ios, '17.0'
use_frameworks!

target 'xcalp' do
  # Networking
  pod 'Alamofire', '~> 5.8.0'
  
  # Reactive Programming
  pod 'RxSwift', '~> 6.5.0'
  pod 'RxCocoa', '~> 6.5.0'
  
  # UI Components
  pod 'SnapKit', '~> 5.6.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_STRICT_CONCURRENCY'] = 'complete'
    end
  end
end
