disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - array_init
  - attributes
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - convenience_type
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - missing_docs
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - switch_case_on_newline
  - vertical_parameter_alignment_on_call

included:
  - apps/ios/clinic/Sources
  - apps/ios/clinic/Tests

excluded:
  - Carthage
  - Pods
  - .build
  - apps/ios/clinic/Sources/XcalpClinic/Resources
  - "**/*.generated.swift"

analyzer_rules:
  - unused_import
  - unused_declaration

force_cast: warning
force_try: warning
force_unwrapping: warning

line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 15
  error: 25

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
    - ok
    - on
    - to
    - up
    - x
    - y
    - z

type_name:
  min_length:
    warning: 3
  max_length:
    warning: 40

reporter: "xcode"